name: Manual Helm Install

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Select a values file"
        required: true
        type: choice
        options:
          - concieragent-vs-chart
          - demo-chatbot-vs-chart
          - hologram-gov-id-verifier-vs-chart
          - pymediasoup-client-chart
          - hologram-gov-id-issuer-vs-chart
          - vision-service-chart
          - webrtc-server-chart
      namespace:
        description: "Kubernetes namespace of the release"
        required: true
        type: choice
        options:
          - demos

jobs:
  install:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Common Kube Setup
        uses: 2060-io/devops/actions/setup-kube@main
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Run kubectl command
        run: |
          echo "Kubeconfig path is automatically set to: $KUBECONFIG"
          kubectl version
          kubectl get pods

      - name: Helm Deploy
        uses: 2060-io/devops/actions/helm-deploy@main
        with:
          environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
          namespace: ${{ inputs.namespace }}
          valuesDir: values
          overridesDir: prod
          domain: ${{ vars.DOMAIN }}
          release: ${{ inputs.release }}
