name: Promote Values File from Dev to Main

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Select a values file"
        required: true
        type: choice
        options:
          - concieragent-vs-chart
          - demo-chatbot-vs-chart
          - hologram-gov-id-verifier-vs-chart
          - pymediasoup-client-chart
          - hologram-gov-id-issuer-vs-chart
          - vision-service-chart
          - webrtc-server-chart
      prodFolder:
        description: "Target folder for production values (default: prod, change with caution)"
        required: false
        default: "prod"
      valuesFolder:
        description: "Target folder for shared values (default: values, change with caution)"
        required: false
        default: "values"

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set file name
        run: echo "FILENAME=${{ inputs.release }}.yaml" >> $GITHUB_ENV

      - name: Find matching files in prod and values
        run: |
          FILES=""
          if [ -d "${{ inputs.prodFolder }}" ]; then
            FILES+=" $(find "${{ inputs.prodFolder }}" -type f -name "${FILENAME}")"
          fi
          if [ -d "${{ inputs.valuesFolder }}" ]; then
            FILES+=" $(find "${{ inputs.valuesFolder }}" -type f -name "${FILENAME}")"
          fi

          FILES=$(echo "$FILES" | xargs) # limpiar espacios extra

          if [ -z "$FILES" ]; then
            echo "No matching files found for ${FILENAME} in ${{ inputs.prodFolder }} or ${{ inputs.valuesFolder }}"
            exit 1
          fi
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Checkout files from dev branch
        run: |
          git fetch origin dev:dev
          for file in $FILES; do
            git checkout dev -- "$file"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deploy): promote ${{ env.FILENAME }} from dev to main"
          title: "chore(deploy): promote ${{ env.FILENAME }} from dev"
          body: |
            This PR promotes `${{ env.FILENAME }}` from the `dev` branch to `main` 
            in the `${{ inputs.prodFolder }}` and `${{ inputs.valuesFolder }}` folders.

            Note: Changing the `prodFolder` or `valuesFolder` inputs can affect deployment consistency. 
            Do so only if you understand the implications.
          branch: promote/${{ inputs.release }}-from-dev
          base: main
