// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // Example: "Learn" section → manual top-level, auto sub-sections
    learnSidebar: [
      {
        type: 'category',
        label: 'Learn',
        items: [
          {
            type: 'autogenerated',
            dirName: 'learn',  // auto-generate from this subfolder
          },
          
        ],
      },
      /*
      {
        type: 'category',
        label: 'Verifiable Trust',
        items: [
         
          {
            type: 'autogenerated',
            dirName: 'learn/verifiable-trust',  // auto-generate from this subfolder
          },
          
        ],
      },*/
      
    ],
  
    buildSidebar: [
        {
          type: 'category',
          label: 'Build',
          items: [
            'build/intro',
            
          ],
        },
        {
            type: 'category',
            label: 'Getting Started',
            items: [
             
              {
                type: 'autogenerated',
                dirName: 'build/getting-started',  // auto-generate from this subfolder
              },
              
            ],
          },
          
    ],

    
    // You can add more sidebars if needed (ex: API reference, specs, etc.)
  };
  
  module.exports = sidebars;
  